-- Import games from src/data/games.ts

-- Insert tags
INSERT INTO tags (slug, name) VALUES ('strategy', 'Strategy') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('battle', 'Battle') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('multiplayer', 'Multiplayer') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('building', 'Building') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('action', 'Action') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('rpg', 'RPG') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('pvp', 'PvP') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('brainrot', 'Brainrot') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('clicker', 'Clicker') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('funny', 'Funny') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('meme', 'Meme') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('casual', 'Casual') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('idle', 'Idle') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('3d', '3D') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('racing', 'Racing') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('io', 'IO') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('shooter', 'Shooter') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('incremental', 'Incremental') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('skill', 'Skill') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('arcade', 'Arcade') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('physics', 'Physics') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('adventure', 'Adventure') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('puzzle', 'Puzzle') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('roblox', 'Roblox') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('music', 'Music') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('parkour', 'Parkour') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('collection', 'Collection') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('brain', 'Brain') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('relaxing', 'Relaxing') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('creative', 'Creative') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('memory', 'Memory') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('tower-defense', 'Tower Defense') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('animal', 'Animal') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('snake', 'Snake') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('grow', 'Grow') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('collect', 'Collect') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('visual-novel', 'Visual Novel') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('horror', 'Horror') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('dark', 'Dark') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('yandere', 'Yandere') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('dating-sim', 'Dating Sim') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('creepy', 'Creepy') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('survival', 'Survival') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('psychological', 'Psychological') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('first-person', 'First-Person') ON CONFLICT (slug) DO NOTHING;
INSERT INTO tags (slug, name) VALUES ('point-and-click', 'Point and Click') ON CONFLICT (slug) DO NOTHING;

-- Insert games
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('goodgame-empire', 'Goodgame Empire', 'https://example.com/images/thumbnails/goodgame-empire.png', 'https://www.gameflare.com/embed/goodgame-empire/', 'Goodgame Empire - An exciting unblocked game. Play now!', 4.5, 2500000, '2025-01-25', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('perfect-orbit', 'Perfect Orbit', 'https://example.com/images/thumbnails/perfect-orbit.png', 'https://games.yoplay.io/perfect-orbit/', 'Perfect Orbit - An exciting arcade sports game. Play now!', 5.0, 125000, '2025-01-25', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('italian-neuro-animals', 'Italian Neuro Animals', 'https://example.com/images/thumbnails/italian-neuro-animals.png', 'https://app-425300.games.s3.yandex.net/425300/wz50sfyyyszgj510yap7bsy1guf7s7gy_brotli/index.html?sdk=%2Fsdk%2F_%2Fv2.dfed038c116f559b5fee.js#origin=https%3A%2F%2Fplayhop.com&app-id=425300&device-type=desktop', 'Italian Neuro Animals - An exciting unblocked game. Play now!', 4.4, 16500, '2025-01-23', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('crazy-sprunki-3d', 'Crazy Sprunki 3D', 'https://example.com/images/thumbnails/crazy-sprunki-3d.png', 'https://www.gameflare.com/embed/crazy-sprunki-3d/', 'Crazy Sprunki 3D - An exciting unblocked game. Play now!', 4, 850000, '2025-01-22', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('kart-bros', 'Kart Bros', 'https://example.com/images/thumbnails/kart-bros.png', 'https://www.gameflare.com/embed/kart-bros/', 'Kart Bros - An exciting unblocked game. Play now!', 4.8, 8500000, '2025-01-21', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('smash-karts', 'Smash Karts', 'https://example.com/images/thumbnails/smash-karts.png', 'https://www.gameflare.com/embed/smash-karts/', 'Smash Karts - An exciting unblocked game. Play now!', 4.2, 5000000, '2025-01-13', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('1v1-lol', '1v1 LOL', 'https://example.com/images/thumbnails/1v1-lol.jpg', 'https://www.gameflare.com/embed/1v1-lol/', '1v1 LOL - An exciting unblocked game. Play now!', 4.4, 80000000, '2025-01-12', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('bro-royale', 'Bro Royale', 'https://example.com/images/thumbnails/bro-royale.png', 'https://www.gameflare.com/embed/bro-royale/', 'Bro Royale - An exciting unblocked game. Play now!', 5, 125000, '2025-01-20', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('brainrot-clicker', 'Brainrot Clicker', 'https://example.com/images/thumbnails/brainrot-clicker.webp', 'https://www.gameflare.com/embed/brainrot-clicker/', 'Brainrot Clicker - An exciting unblocked game. Play now!', 4.9, 15234, '2025-01-05', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('brainrot-hook-swing', 'Brainrot Hook Swing', 'https://example.com/images/thumbnails/brainrot-hook-swing.jpg', 'https://www.gameflare.com/embed/brainrot-hook-swing/', 'Brainrot Hook Swing - An exciting unblocked game. Play now!', 4.5, 18567, '2024-12-20', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('italian-brainrot-baby-clicker', 'Italian Brainrot Baby Clicker', 'https://example.com/images/thumbnails/italian-brainrot-baby-clicker.jpg', 'https://www.gameflare.com/embed/italian-brainrot-baby-clicker/', 'Italian Brainrot Baby Clicker - An exciting unblocked game. Play now!', 4.8, 8923, '2025-01-08', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('steal-the-italian-brainrot', 'Steal The Italian Brainrot', 'https://example.com/images/thumbnails/steal-the-italian-brainrot.png', 'https://now.gg/apps/roblox-corporation/5349/roblox.html', 'Steal The Italian Brainrot - An exciting unblocked game. Play now!', 4.9, 18923, '2024-12-15', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('obby-my-singing-brainrot', 'Obby: My Singing Brainrot', 'https://example.com/images/thumbnails/obby-my-singing-brainrot.jpg', 'https://www.roblox.com/games/start?placeId=123456789', 'Obby: My Singing Brainrot - An exciting unblocked game. Play now!', 5, 25678, '2024-12-10', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('steal-brainrot-online', 'Steal Brainrot Online', 'https://example.com/images/thumbnails/steal-brainrot-online.png', 'https://www.roblox.com/games/start?placeId=987654321', 'Steal Brainrot Online - An exciting unblocked game. Play now!', 4.3, 12456, '2024-12-01', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('steal-brainrot-new-animals', 'Steal Brainrot: New Animals', 'https://example.com/images/thumbnails/steal-brainrot-new-animals.png', 'https://www.roblox.com/games/start?placeId=456789123', 'Steal Brainrot: New Animals - An exciting unblocked game. Play now!', 3.5, 3421, '2025-01-10', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('fix-da-brainrot', 'Fix Da Brainrot', 'https://example.com/images/thumbnails/fix-da-brainrot.jpg', 'https://www.gameflare.com/embed/fix-da-brainrot/', 'Fix Da Brainrot - An exciting unblocked game. Play now!', 5, 32145, '2024-11-25', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('memory-brainrot', 'Memory Brainrot', 'https://example.com/images/thumbnails/memory-brainrot.jpg', 'https://www.gameflare.com/embed/memory-brainrot/', 'Memory Brainrot - An exciting unblocked game. Play now!', 5, 28934, '2024-11-20', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('italian-brainrot-clicker-2', 'Italian Brainrot Clicker 2', 'https://example.com/images/thumbnails/italian-brainrot-clicker-2.png', 'https://www.gameflare.com/embed/italian-brainrot-clicker-2/', 'Italian Brainrot Clicker 2 - An exciting unblocked game. Play now!', 4, 6789, '2025-01-09', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('plants-vs-brainrots', 'Plants vs Brainrots', 'https://example.com/images/thumbnails/plants-vs-brainrots.jpg', 'https://www.gameflare.com/embed/plants-vs-brainrots/', 'Plants vs Brainrots - An exciting unblocked game. Play now!', 4.1, 21567, '2024-11-15', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('crazy-cattle-3d', 'Crazy Cattle 3D', 'https://example.com/images/thumbnails/crazy-cattle-3d.jpg', 'https://www.gameflare.com/embed/crazy-cattle-3d/', 'Crazy Cattle 3D - An exciting unblocked game. Play now!', 4.6, 2156, '2025-01-11', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('las-sis-steal-brainrot', 'Las Sis (Steal a Brainrot)', 'https://example.com/images/thumbnails/las-sis-steal-brainrot.jpg', 'https://www.roblox.com/games/start?placeId=789123456', 'Las Sis (Steal a Brainrot) - An exciting unblocked game. Play now!', 4.7, 4303, '2025-01-20', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('little-big-snake', 'Little Big Snake', 'https://example.com/images/thumbnails/little-big-snake.png', 'https://www.gameflare.com/embed/little-big-snake/', 'Little Big Snake - An exciting unblocked game. Play now!', 5, 8500000, '2025-01-21', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('cheese-chompers-3d', 'Cheese Chompers 3D', 'https://example.com/images/thumbnails/cheese-chompers-3d.png', 'https://www.gameflare.com/embed/cheese-chompers-3d/', 'Cheese Chompers 3D - An exciting unblocked game. Play now!', 5, 1, '2025-01-21', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('crazy-sheep-3d', 'Crazy Sheep 3D', 'https://example.com/images/thumbnails/crazy-sheep-3d.png', 'https://www.gameflare.com/embed/crazy-sheep-3d/', 'Crazy Sheep 3D - An exciting unblocked game. Play now!', 4.1, 45000, '2025-01-22', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('rocket-fortress', 'Rocket Fortress', 'https://example.com/images/thumbnails/rocket-fortress.png', 'https://www.gameflare.com/embed/rocket-fortress/', 'Rocket Fortress - An exciting unblocked game. Play now!', 5, 125000, '2025-01-22', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('the-freak-circus', 'The Freak Circus', 'https://example.com/images/thumbnails/the-freak-circus.jpg', 'https://html-classic.itch.zone/html/14081436/index.html', 'The Freak Circus - An exciting unblocked game. Play now!', 4.9, 2514000, '2025-10-23', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO games (slug, title, cover, play_url, description, rating, play_count, released_at, is_active) VALUES ('no-im-not-a-human', 'No, I\'m not a Human', '/images/thumbnails/no-im-not-a-human.png', 'https://d.ulyagames.com/games/no-im-not-a-human/', 'No, I\'m not a Human - Psychological horror survival game. Play now!', 4.7, 850000, '2025-10-23', true) ON CONFLICT (slug) DO NOTHING;

-- Link games to tags
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'goodgame-empire' AND t.slug = 'strategy' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'goodgame-empire' AND t.slug = 'battle' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'goodgame-empire' AND t.slug = 'multiplayer' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'goodgame-empire' AND t.slug = 'building' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'goodgame-empire' AND t.slug = 'action' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'battle-arena' AND t.slug = 'battle' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'battle-arena' AND t.slug = 'rpg' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'battle-arena' AND t.slug = 'strategy' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'battle-arena' AND t.slug = 'action' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'battle-arena' AND t.slug = 'multiplayer' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'battle-arena' AND t.slug = 'pvp' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'italian-neuro-animals' AND t.slug = 'brainrot' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'italian-neuro-animals' AND t.slug = 'clicker' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'italian-neuro-animals' AND t.slug = 'funny' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'italian-neuro-animals' AND t.slug = 'meme' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'italian-neuro-animals' AND t.slug = 'casual' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'italian-neuro-animals' AND t.slug = 'idle' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'crazy-sprunki-3d' AND t.slug = '3d' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'crazy-sprunki-3d' AND t.slug = 'battle' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'crazy-sprunki-3d' AND t.slug = 'multiplayer' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'crazy-sprunki-3d' AND t.slug = 'action' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'crazy-sprunki-3d' AND t.slug = 'funny' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'crazy-sprunki-3d' AND t.slug = 'casual' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'kart-bros' AND t.slug = 'racing' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'kart-bros' AND t.slug = 'multiplayer' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'kart-bros' AND t.slug = 'io' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'kart-bros' AND t.slug = 'action' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'kart-bros' AND t.slug = 'battle' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'smash-karts' AND t.slug = 'battle' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'smash-karts' AND t.slug = 'multiplayer' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'smash-karts' AND t.slug = 'racing' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'smash-karts' AND t.slug = 'action' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'smash-karts' AND t.slug = 'io' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = '1v1-lol' AND t.slug = 'battle' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = '1v1-lol' AND t.slug = 'multiplayer' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = '1v1-lol' AND t.slug = 'shooter' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = '1v1-lol' AND t.slug = 'building' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = '1v1-lol' AND t.slug = 'action' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'bro-royale' AND t.slug = 'battle' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'bro-royale' AND t.slug = 'shooter' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'bro-royale' AND t.slug = 'multiplayer' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'bro-royale' AND t.slug = 'action' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'bro-royale' AND t.slug = 'io' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'brainrot-clicker' AND t.slug = 'brainrot' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'brainrot-clicker' AND t.slug = 'clicker' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'brainrot-clicker' AND t.slug = 'idle' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'brainrot-clicker' AND t.slug = 'incremental' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'brainrot-clicker' AND t.slug = 'casual' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'brainrot-hook-swing' AND t.slug = 'brainrot' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'brainrot-hook-swing' AND t.slug = 'action' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'brainrot-hook-swing' AND t.slug = 'skill' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'brainrot-hook-swing' AND t.slug = 'arcade' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'brainrot-hook-swing' AND t.slug = 'physics' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'italian-brainrot-baby-clicker' AND t.slug = 'brainrot' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'italian-brainrot-baby-clicker' AND t.slug = 'clicker' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'italian-brainrot-baby-clicker' AND t.slug = 'funny' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'italian-brainrot-baby-clicker' AND t.slug = 'meme' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'italian-brainrot-baby-clicker' AND t.slug = 'casual' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'steal-the-italian-brainrot' AND t.slug = 'brainrot' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'steal-the-italian-brainrot' AND t.slug = 'adventure' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'steal-the-italian-brainrot' AND t.slug = 'strategy' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'steal-the-italian-brainrot' AND t.slug = '3d' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'steal-the-italian-brainrot' AND t.slug = 'puzzle' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'obby-my-singing-brainrot' AND t.slug = 'brainrot' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'obby-my-singing-brainrot' AND t.slug = 'roblox' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'obby-my-singing-brainrot' AND t.slug = 'music' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'obby-my-singing-brainrot' AND t.slug = 'meme' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'obby-my-singing-brainrot' AND t.slug = 'adventure' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'obby-my-singing-brainrot' AND t.slug = 'parkour' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'steal-brainrot-online' AND t.slug = 'brainrot' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'steal-brainrot-online' AND t.slug = 'multiplayer' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'steal-brainrot-online' AND t.slug = 'roblox' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'steal-brainrot-online' AND t.slug = 'meme' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'steal-brainrot-online' AND t.slug = 'strategy' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'steal-brainrot-online' AND t.slug = 'casual' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'steal-brainrot-new-animals' AND t.slug = 'brainrot' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'steal-brainrot-new-animals' AND t.slug = 'roblox' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'steal-brainrot-new-animals' AND t.slug = 'meme' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'steal-brainrot-new-animals' AND t.slug = 'collection' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'steal-brainrot-new-animals' AND t.slug = 'arcade' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'steal-brainrot-new-animals' AND t.slug = 'casual' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'fix-da-brainrot' AND t.slug = 'brainrot' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'fix-da-brainrot' AND t.slug = 'puzzle' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'fix-da-brainrot' AND t.slug = 'casual' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'fix-da-brainrot' AND t.slug = 'brain' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'fix-da-brainrot' AND t.slug = 'relaxing' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'fix-da-brainrot' AND t.slug = 'creative' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'memory-brainrot' AND t.slug = 'brainrot' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'memory-brainrot' AND t.slug = 'memory' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'memory-brainrot' AND t.slug = 'puzzle' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'memory-brainrot' AND t.slug = 'meme' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'memory-brainrot' AND t.slug = 'brain' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'memory-brainrot' AND t.slug = 'casual' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'italian-brainrot-clicker-2' AND t.slug = 'brainrot' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'italian-brainrot-clicker-2' AND t.slug = 'clicker' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'italian-brainrot-clicker-2' AND t.slug = 'meme' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'italian-brainrot-clicker-2' AND t.slug = 'idle' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'italian-brainrot-clicker-2' AND t.slug = 'funny' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'italian-brainrot-clicker-2' AND t.slug = 'casual' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'plants-vs-brainrots' AND t.slug = 'brainrot' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'plants-vs-brainrots' AND t.slug = 'strategy' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'plants-vs-brainrots' AND t.slug = 'tower-defense' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'plants-vs-brainrots' AND t.slug = 'meme' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'plants-vs-brainrots' AND t.slug = 'casual' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'plants-vs-brainrots' AND t.slug = 'funny' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'crazy-cattle-3d' AND t.slug = 'battle' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'crazy-cattle-3d' AND t.slug = 'multiplayer' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'crazy-cattle-3d' AND t.slug = 'strategy' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'crazy-cattle-3d' AND t.slug = 'casual' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'crazy-cattle-3d' AND t.slug = 'funny' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'crazy-cattle-3d' AND t.slug = '3d' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'crazy-cattle-3d' AND t.slug = 'animal' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'las-sis-steal-brainrot' AND t.slug = 'roblox' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'las-sis-steal-brainrot' AND t.slug = 'meme' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'las-sis-steal-brainrot' AND t.slug = 'brainrot' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'las-sis-steal-brainrot' AND t.slug = 'casual' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'little-big-snake' AND t.slug = 'io' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'little-big-snake' AND t.slug = 'multiplayer' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'little-big-snake' AND t.slug = 'snake' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'little-big-snake' AND t.slug = 'grow' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'little-big-snake' AND t.slug = 'collect' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'little-big-snake' AND t.slug = 'animal' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'cheese-chompers-3d' AND t.slug = 'battle' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'cheese-chompers-3d' AND t.slug = 'multiplayer' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'cheese-chompers-3d' AND t.slug = 'casual' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'cheese-chompers-3d' AND t.slug = 'funny' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'cheese-chompers-3d' AND t.slug = '3d' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'cheese-chompers-3d' AND t.slug = 'animal' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'crazy-sheep-3d' AND t.slug = '3d' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'crazy-sheep-3d' AND t.slug = 'action' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'crazy-sheep-3d' AND t.slug = 'adventure' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'crazy-sheep-3d' AND t.slug = 'casual' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'crazy-sheep-3d' AND t.slug = 'animal' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'rocket-fortress' AND t.slug = 'rpg' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'rocket-fortress' AND t.slug = 'clicker' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'rocket-fortress' AND t.slug = 'strategy' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'rocket-fortress' AND t.slug = 'action' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'rocket-fortress' AND t.slug = 'incremental' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'the-freak-circus' AND t.slug = 'visual-novel' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'the-freak-circus' AND t.slug = 'horror' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'the-freak-circus' AND t.slug = 'dark' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'the-freak-circus' AND t.slug = 'yandere' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'the-freak-circus' AND t.slug = 'dating-sim' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'the-freak-circus' AND t.slug = 'creepy' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'no-im-not-a-human' AND t.slug = 'horror' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'no-im-not-a-human' AND t.slug = 'survival' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'no-im-not-a-human' AND t.slug = 'puzzle' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'no-im-not-a-human' AND t.slug = 'psychological' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'no-im-not-a-human' AND t.slug = 'first-person' ON CONFLICT DO NOTHING;
INSERT INTO game_tags (game_id, tag_id) SELECT g.id, t.id FROM games g, tags t WHERE g.slug = 'no-im-not-a-human' AND t.slug = 'point-and-click' ON CONFLICT DO NOTHING;
